const ipTypeFields = {
  advRou: true,
  LSANetMask: true,
  WINSRplOwn: true,
  hostAddr: true,
  tunSrcAddr: true,
  tunDstAddr: true,
  intLocAddr: true,
  intDstAddr: true,
  nextHop: true,
  NASIPAddr: true,
  curAddr: true,
  newCliAddr: true,
  svcAddr: true,
  fraIPAddr: true,
  unrSrcAddr: true,
  unrDstAddr: true,
  IPAddr: true,
  group_address: true,
  source_addr: true,
  senderIPAddr: true,
  srcHostAddr: true,
  router_id: true,
  reflected_from_ip: true,
  xor_mapped_addr_ip: true,
  IPaddress: true,
  anchor_address: true,
  realSrcIPAddr: true,
  realDstIPAddr: true,
  dstIPAddr: true,
  dr: true,
  aggAddr: true,
  cluIDList: true,
  ip_addr: true,
  subnet_mask: true,
  sip: true,
  sip_sip: true,
  subMask: true,
  dip: true,
  rouID: true,
  sip_dip: true,
  cip: true,
  fip: true,
};

const emunTypeFields = {
  data_type: {1:"音频",2:"视频",3:"未知类型",4:"信令"},
  met:{0:"未知",1:"GET",2:"POST"},
  frtype:{1:"子站", 0:"主校区"},
  aleLev:{1:"Warning",2:"Fatal"},
  cerStat:{0:"good", 1:"revoked",2:"unknown"},
  aleDes:{
    0:"Close Notify",
    10:"Unexpected Message",
    20:"Bad Record MAC" ,
    21:"Decryption Failed",
    22:"Record Overflow",
    30:"Decompression Failure",
    40:"Handshake Failure",
    41:"No Certificate",
    42:"Bad Certificate",
    43:"Unsupported Certificate",
    44:"Certificate Revoked",
    45:"Certificate Expired",
    46:"Certificate Unknown",
    47:"Illegal Parameter",
    48:"Unknown CA",
    49:"Access Denied",
    50:"Decode Error",
    51:"Decrypt Error",
    60:"Export Restriction",
    70:"Protocol Version",
    71:"Insufficient Security",
    80:"Internal Error",
    86:"Inappropriate Fallback",
    90:"User Canceled",
    100:"No Renegotiation",
    110:"Unsupported Extension",
    111:"Certificate Unobtainable",
    112:"Unrecognized Name",
    113:"Bad Certificate Status Response",
    114:"Bad Certificate Hash Value",
    115:"Unknown PSK Identity",
    120:"No application Protocol",
  },
  handshark_type:{
    0:"HELLO_REQUEST",
    1:"CLIENT_HELLO",
    2:"SERVER_HELLO",
    3:"HELLO_VERIFY_REQUEST",
    4:"NEWSESSION_TICKET",
    11:"CERTIFICATE",
    12:"SERVER_KEY_EXCHG",
    13:"CERT_REQUEST",
    14:"SVR_HELLO_DONE",
    15:"CERT_VERIFY",
    16:"CLIENT_KEY_EXCHG",
    20:"FINISHED",
    21:"CERT_URL",
    22:"CERT_STATUS",
    23:"SUPPLEMENTAL_DATA",
    67:"ENCRYPTED_EXTS",
  },
  cliVer:{3:"SSL3.0",769:"TLS1.0",770:"TLS1.1",771:"TLS1.2"},
  cliComMet:{0:"null",1:"Deflate"},
  srvVer:{768:"SSL3.0",769:"TLS1.0",770:"TLS1.1",771:"TLS1.2"},
  srvComprMet:{0:"null",1:"Deflate"},
  extTypeInSSL:{10:"elliptic_curve",11:"ec_point_format",65281:"renegotiation_info"},
  cliEllCurPoiFor:{0:"uncompressed",1:"ansiX962_compressed_prim",2:"ansiX962_compressed_char"},
  srvEllCurPoiFor:{0:"uncompressed",1:"ansiX962_compressed_prim",2:"ansiX962_compressed_char"},
  respID:{0:"byname（采用名称hash作为回应）", 1:"bykey（采用公钥hash作为回应）"},
  extTypeInssl:{10:"elliptic_curve",11:"ec_point_format",65281:"renegotiation_info"},
  cliellCurPoifor:{0:"uncompressed",1:"ansiX962_compressed_prim",2:"ansiX962_compressed_char"},
  srvEllCurpoifor:{0:"uncompressed",1:"ansiX962_compressed_prim",2:"ansiX962_compressed_char"},
  fileMode:{16384 :"文件夹", 32768:"文件"},
  bacType:{160 :"完全备份", 128:"增量备份", 96:"文件夹备份"},
  // SNMP
  PDUType:{0:"get-request",1:"get-next-request",2:"get-response",3:"set-request",4:"trap"},
  objVal:{1:"bool",2:"int",4:"str",64:"ipaddr",255:"other"},
  secMode:{0:"任何模型",1:"采用SNMPv1安全模型",2:"采用SNMPv2c安全模型",3:"采用SNMPv3安全模型"},
  initVer:{a:"（1.0版）",14:"（2.0版）"},
  respVer:{a:"（1.0版）",14:"（2.0版）"},
  dOI:{0:"（null）",1:"（IPSEC）"},
  origin:{0:"IGP",2:"EGP",3:"INCOMPLETE"},
  addrFam:{1:"IPv4",2:"IPv6"},
  SAFI:{1:"Unicast",4:"Labeled Unicast",128:"Labeled VPN Unicast"},
  // RIP
  cmd:{1:"请求",2:"相应"},
  addrFamID:{0:"对路由器或主机的整个路由表进行请求的指示",2:"对IPV4地址族请求的指示",65535:"指示认证请求"},
  infoType:{1:"Unicast",4:"Labeled Unicast",128:"Labeled VPN Unicast"},

  mail_type:{ 2: "SMTP", 3: "POP3", 4: "IMAP", 5: "MMS", 4096: "WEBMAIL" },
  addr_type:{ 1: "FROM", 2: "TO", 3: "CC", 4: "BCC", 5: "MAILFROM", 6: "RCPTTO", 4096: "WEBMAIL" },
  message:{ 1: "KEEPALIVE Message", 2: "OPEN Message" },
  message_type:{1: "hello", 2: "Database Description", 3: "link state request", 4: "link state update", 5: "link state acknowledgment"},
  calling_flag:{ 0: "正向被叫", 1: "正向主叫", 2: "缺省无信令" },
  action:{0: '',1: "上传", 2: "下载"},
  dec_link:{ 0: "否", 1: "是" },
  subtype:{ 1: "smb1", 2: "smb2", 3: "smb油槽", 4: "smb管道" },
  rep_status:{0:"OCSP_STATUS_SUCCESSFUL",1:"OCSP_STATUS_MALFORMEDREQUEST",2:"OCSP_STATUS_INTERNALERROR",3:"OCSP_STATUS_TRYLATER",
              4:"OCSP_STATUS_SIGREQUIRED",5:"OCSP_STATUS_UNAUTHORIZED",6:"OCSP_STATUS_REQNOSTATUS"},
  wa:{0:"未知",1:"get",2:"post"},

  es:{1: "加密", 2: "未加密", 3: "未知", 4: "待判定"},

  ia:{1: "上线", 2: "下线", 3: "聊天"},
  at:{1: "上传", 2: "下载"},
  proxy_type:{1: "socks", 2: "http connect"},
  rs:{0: "OCSP_STATUS_SUCCESSFUL", 1: "OCSP_STATUS_MALFORMEDREQUEST", 2: "OCSP_STATUS_INTERNALERROR", 3: "OCSP_STATUS_TRYLATER", 4: "OCSP_STATUS_SIGREQUIRED", 5: "OCSP_STATUS_UNAUTHORIZED", 6: "OCSP_STATUS_REQNOSTATUS"},
  IMZK_ACTION:{1: "上线", 2: "下线"},
  SMB_ACTION:{1: "上传", 2: "下载"},
  FTP_ACTION:{1: "上传", 2: "下载"},
  IMZK_TYPE:{1: "QQ"},
  OCSP_TYPE:{1: "request", 2: "response"},
  OSPF_TYPE:{1: "hello", 2: "Database Description", 3: "link state request", 4: "link state update", 5: "link state acknowledgment"},
  mpt:{6: "TCP", 17: "UDP"},
  ai:{0: "邮件附件从1开始编号"},
  et:{2: "smtp", 3: "pop", 4:"imap"},
  pt:{6: "TCP", 17: "UDP"},
  sip_pt:{6: "TCP", 17: "UDP"},
  dns_type:{1: "DNS", 2: "MDNS"},
  pro:{"1":"HTTP初筛选","2":"保留","3":"保留","4":"保留","5":"WEB纯文本","6":"IM","7":"VOIP","8":"TELNET","9":"保留","10":"保留","11":"GTP-V1","12":"GTP-V2","13":"BGP","14":"SMB","15":"SSL","16":"A11","17":"MOBILE-INFO","18":"VNC","19":"RADIUS","20":"IGMP-V2","21":"IGMP-V3","22":"PIM","23":"NETBIOS","24":"VRRP","25":"OSPF","26":"ARP","27":"CFLOW","28":"H248","29":"RDP","30":"OSPF","31":"空闲","32":"SQL","33":"FTP基本信息","34":"HTTP-MINI","35":"EML-MINI","36":"SSL-MINI","37":"SMB2","38":"RAW-MAIL","39":"代理信息","40":"文本抽取","41":"原始报文","42":"NTLM","43":"OCSP","44":"DCERPC","45":"SSH","46":"PPTP","47":"L2TP","48":"ISAKMP","49":"SNMP","50":"NTP数据消息","51":"NTP控制消息","52":"RIP","53":"XMPP","54":"ICMP","55":"RTP","56":"diameter","57":"STUN","58":"RTP_DEFRAG","59":"IPCP","60":"SNAP","61":"LLC","62":"X11","63":"MPLS","64":"EIGRP","65":"GRE","66":"LDAP、CLDAP","67":"SIP","68":"DNS(v6)","69":"RTMP","70":"DHCP","71":"LDP","72":"TFTP","73":"KERBEROS","80":"ESP","81":"RSVP","82":"AH","83":"WINS","84":"RSYNC","85":" ","86":"CHAP","87":"PAP","88":"CDP","89":"LCP","90":"T38","91":"NNTP","92":"iec104","93":"dnp3","94":"rsync","96":"x11","97":"ccp","98":"ISIS","99":"pppoe","100":"保留","101":"EMAIL","102":"FTP日志","112":"FTP文件数据","122":"H225","123":"H245","129":"活动事件报告","144":"NFS","145":"MEGACO","146":"移动设备信息","147":"认证信息","148":"stp","149":"sctp","150":"西宁VPN","151":"西宁访问代理(PROXY)","152":"远程控制（西宁）（remote_ctrl）","153":"P2P下载（p2p）","154":"突防工具(overnet)","165":"短信(SMS)","166":"rtsp","167":"原始数据包（西宁）","168":"微信（mm）","169":"社交网络","170":"图片活动","171":"rtcp","172":"ssdp","173":"ipx","174":"微信实时信息","180":"http分段重组","181":"xn_https"},
  ds:{1: "单向C2S(1)", 2: "单向 S2C(2)", 3: "双向数据(3)"},
  res_info_type:{".png": "png图片", ".html": "HTML", ".plain": "纯文本", ".xml": "XML", ".gif": "GIF图片", ".xhtml+xml": "XHTML", ".atom+xml": "Atom XML聚合", ".json": "JSON", ".pdf": "PDF", ".msword": "Word", ".x-www-from-urlencoded": "表单k/v默认提交", ".octet-stream": "二进制流", ".form-data": "表单文件上传"},
  cert_type: {1: "客户端->服务器", 2: "服务器->客户端"},
  exScanType: {1: "nmap扫描", 2: "ssl扫描"},
  linkLayerType: { 0: "RAWIP", 1: "PPP" , 2: "ATM" },
}

const timeTypeFields = {
  srvGMTUniTime: true,
  cliGMTUniTime: true,
  TTL: true,
  stopTime: true,
  staTime: true,
  cap_timestamp: true,
  ct: true,
  ctms: true,
  tm_sec: true,
  sip_ct: true,
  sip_ctms: true,
  analysis_timestamp: true,
}

export {
  ipTypeFields, emunTypeFields, timeTypeFields,
}
