// 页面一些可配置模块的默认配置项，添加是记得加上相关模块的名称
module.exports = {
  // 输出配置模块默认配置项
    defaultOutputMenus: [
        {hidden:'0',id:'1',key:'udpOutPut',label:'UDP输出配置'},
        {hidden:'0',id:'2',key:'softbus',label:'总线输出配置'},
        {hidden:'0',id:'3',key:'saveDisk',label:'存盘输出配置'},
        {hidden:'0',id:'4',key:'showFile',label:'文件展示'},
        {hidden:'0',id:'5',key:'tcp',label:'TCP输出配置'},
        {hidden: '1',id:'6',key:'yoyo',label:'YOYO总线输出配置'},
      ],

  // defaultOutputMenus
  defaultOutputMenus: [{hidden:'0',id:'1',key:'udpOutPut',label:'UDP输出配置'},{hidden:'0',id:'2',key:'softbus',label:'总线输出配置'},{hidden:'0',id:'3',key:'saveDisk',label:'存盘输出配置'},{hidden:'0',id:'4',key:'showFile',label:'文件展示'},{hidden:'0',id:'5',key:'tcp',label:'TCP输出配置'},{hidden: '1',id:'6',key:'yoyo',label:'YOYO总线输出配置'}],
  // 发射机器基础配置
  launchWebcastConfig: {
    "bandCardConfigType":"1",
    "channelCalibation":"1",
    "sendTimeBias":"0",
    "isOpenPasswordLock":"0",
    "isShowFreqColumnSetBtn":"1",
    "isShowSystemDelay":"1",
    "netStateStationStateComponentTitle":"",
    "passwordLockPassword":"",
    "passwordLockUserName":"",
    "rollOffFactorValue":"1.45",
    "sendGainInputSnrRange":{"max":255,"min":1},
    "sendNetStateDetailInfoTitle":"通道信息详情",
    "siginalFollowAntennaType":"0",
    "siginalType":["LinkWayS2","HX/HN"],
    "stationOnlineMaxTime":5,
  },
  // 页面默认操作按钮
  stationWebButtons: [
    {hidden:'1',id:'1',key:'networkState',icon:'icon-earth-line',label:'通信网态势'},
    {hidden:'0',id:'2',key:'outputConfig',icon:'icon-shuchupeizhi',label:'输出配置'},
    {hidden:'1',id:'3',key:'saveConfig',icon:'icon-save-3-fill',label:'保存配置'},
    {hidden:'1',id:'4',key:'previewConfig',icon:'icon-yulan',label:'配置预览'},
    {hidden:'0',id:'5',key:'resetCurrent',icon:'icon-shuaxin',label:'当前网重置'},
    {hidden:'1',id:'6',key:'adAcquisite',icon:'icon-shujuku',label:'数据采集'},
    {hidden:'1',id:'7',key:'acquisitionResult',icon:'icon-shujuku',label:'采集结果'},
    {hidden:'1',id:'8',key:'configArea',icon:'icon-guanlian-01',label:'配置空间'}
  ],
  // 个人中心菜单默认配置
  defaultUserMenu: [
    { "hidden": "1", "icon": "setting", "id": "userConfig", "key": "userConfig", "label": "偏好设置", "text": "偏好设置", "name": "userConfig" },
    { "hidden": "1", "icon": "reload", "id": "resetAll", "key": "resetAll", "label": "全网重置", "text": "全网重置", "name": "resetAll" },
    { "hidden": "1", "icon": "deployment-unit", "id": "networkState2", "key": "networkState", "label": "通信网态势" },
    { "hidden": "1", "icon": "apartment", "id": "cluster", "key": "cluster", "label": "集群配置" },
    { "hidden": "1", "icon": "RadarChart", "id": "networkComposition", "key": "networkComposition", "label": "网络组成结构" },
    { "hidden": "1", "icon": "appstore", "id": "companyMode", "key": "companyMode", "label": "厂商模式", "text": "厂商模式", "name": "companyMode"},
    { "hidden": "0", "icon": "line-chart", "id": "systemStatus", "key": "systemStatus", "label": "系统状态", "text": "系统状态", "name": "systemStatus", "disabled": true},
    { "hidden": "1", "icon": "setting", "id": "inverterConfig", "key": "inverterConfig", "label": "变频器设置", "text": "变频器设置", "name": "inverterConfig"},
    { "hidden": "1", "icon": "control", "id": "matrixGain", "key": "matrixGain", "label": "交换矩阵增益配置", "text": "交换矩阵增益配置", "name": "matrixGain"},
    { "hidden": "1", "icon": "key", "id": "keyMannage", "key": "keyMannage", "label": "密钥管理", "text": "密钥管理", "name": "keyMannage"},
    { "hidden": "1", "icon": "setting", "id": "systemSetting", "key": "systemSetting", "label": "系统配置", "text": "系统配置", "name": "systemSetting"},
    { "hidden": "1", "icon": "key", "id": "changePassword", "key": "changePassword", "label": "修改密码", "text": "修改密码", "name": "changePassword"},
    { "hidden": "1", "icon": "download", "id": "download_sdk_file", "key": "download_sdk_file", "label": "SDK数据格式文档", "text": "SDK数据格式文档", "name": "download_sdk_file", "defaultDisabled": true},
    { "hidden": "1", "icon": "download", "id": "download_device_file", "key": "download_device_file", "label": "设备数据格式文档", "text": "设备数据格式文档", "name": "download_device_file", "defaultDisabled": true},
    { "hidden": "1", "icon": "download", "id": "download_environment_file", "key": "download_environment_file", "label": "依赖环境", "text": "依赖环境", "name": "download_environment_file", "defaultDisabled": true},
    { "hidden": "0", "icon": "download", "id": "programZip", "key": "programZip", "label": "软件开发包", "text": "软件开发包", "name": "programZip", "disabled": true},
    { "hidden": "0", "icon": "file", "id": "userManaual", "key": "userManaual", "label": "用户使用手册", "text": "用户使用手册", "name": "userManaual", "disabled": true},
    { "hidden": "1", "icon": "download", "id": "VSPClient", "key": "VSPClient", "label": "发射客户端", "text": "发射客户端", "name": "VSPClient"},
    { "hidden": "1", "icon": "menu", "id": "logList", "key": "logList", "label": "操作日志", "text": "操作日志", "name": "logList"},
    { "hidden": "1", "icon": "poweroff", "id": "poweroff", "key": "poweroff", "label": "一键关机", "text": "一键关机", "name": "poweroff"},
    { "hidden": "1", "icon": "reload", "id": "reload", "key": "reload", "label": "一键重启", "text": "一键重启", "name": "reload"},
    { "hidden": "1", "icon": "sync", "id": "resetNrf", "key": "resetNrf", "label": "重启并恢复系统", "text": "重启并恢复系统", "name": "resetNrf"},
    { "hidden": "1", "icon": "tag", "id": "versionManage", "key": "versionManage", "label": "版本升级", "text": "版本升级", "name": "versionManage"},
    { "hidden": "0", "icon": "user", "id": "authStatus", "key": "authStatus", "label": "授权状态", "text": "授权状态", "name": "authStatus", "disabled": true},
    { "hidden": "0", "icon": "info-circle", "id": "version", "key": "version", "label": "关于", "text": "关于", "name": "version", "disabled": true},
  ],
  defaultBtnList: [
    { "hidden": "0", "id": "adaptiveShow", "key": "adaptiveShow", "label": "自适应" },
    { "hidden": "0", "id": "spreadSpectrumShow", "key": "spreadSpectrumShow", "label": "扩频系数" },
    { "hidden": "0", "id": "frequencyShow", "key": "frequencyShow", "label": "变频器" },
    { "hidden": "0", "id": "adCardShow", "key": "adCardShow", "label": "AD卡" },
    { "hidden": "0", "id": "averageDeep", "key": "averageDeep", "label": "均值深度" },
    { "hidden": "0", "id": "higherConfig", "key": "higherConfig", "label": "高级配置" },
    { "hidden": "1", "id": "vsatInfo", "key": "vsatInfo", "label": "体量提示" },
    { "hidden": "0", "id": "allNetShow", "key": "allNetShow", "label": "全网信息" },
    { "hidden": "1", "id": "EssInfoDisplay", "key": "EssInfoDisplay", "label": "Ess密钥" },
    { "hidden": "1", "id": "IPFraInfoDisplay", "key": "IPFraInfoDisplay", "label": "IP拼包" },
    { "hidden": "1", "id": "syncInfo", "key": "syncInfo", "label": "syncInfo" },
    { "hidden": "0", "id": "columnSetting", "key": "columnSetting", "label": "表格设置" },
    { "hidden": "0", "id": "haveSpectrumSweep", "key": "haveSpectrumSweep", "label": "扫频" },
    { "hidden": "0", "id": "couldChangeRfMod", "key": "couldChangeRfMod", "label": "RF口" },
    { "hidden": "0", "id": "netControlDemodulationShow", "key": "netControlDemodulationShow", "label": "网控解调" },
  ],
  networkStateTabConfig: [
    { "hidden": "1", "key": "old_terminal_time", "name": "终端通联时序" },
    { "hidden": "1", "key": "main_small_carrier", "name": "主小区" },
    { "hidden": "1", "key": "tree_uniq", "name": "树状图" },
    { "hidden": "0", "key": "netstation_relation_topu", "name": "VSAT网关系拓扑" },
    { "hidden": "0", "key": "tree_relation", "name": "VSAT IP设备拓扑" },
    { "hidden": "0", "key": "relation_topu", "name": "VSAT IP设备通联拓扑" },
    { "hidden": "0", "key": "terminal_time", "name": "VSAT终端通联时序" },
    { "hidden": "0", "key": "carrier_combine", "name": "VSAT统计" },
    { "hidden": "0", "key": "small_carrier_count", "name": "VSAT小区统计" },
    { "hidden": "0", "key": "station_copy_count", "name": "主小区抄收数据统计" },
    { "hidden": "0", "key": "main_station_count", "name": "主校区状态统计" },
    { "hidden": "0", "key": "data_analysis", "name": "服务数据统计" },
  ],
  // 通信网态势 服务数据统计 Config
  dataAnalysisConfig: [
    { "hidden": "0", "key": "ip_pie_analysis", "name": "服务IP端口统计" },
    { "hidden": "0", "key": "proto_pie_analysis", "name": "服务协议统计" },
  ],
};
