
module.exports = {
	dark: {
    name: 'dark',
    cssVar: true,
    token: {
      'borderRadiusLG': 'none',
      'colorBgLayout': '#000e2f',
      'colorTextBase': '#ffffff',
      'colorBgBase': '#000e2f',
      'colorInfoBg': '#19325a',
      'colorPrimary': '#1890ff',
      'colorBorder': '#48566e',
      'colorBgContainer': '#19325a',
      'colorBgElevated': '#183a65',
      'borderRadius': 1,
      // 紧凑主题 token
      paddingXXS: 2,
      paddingXS: 4,
      paddingSM: 8,
      padding: 12,
      paddingMD: 16,
      paddingLG: 20,
      paddingXL: 24,
      marginXXS: 2,
      marginXS: 4,
      marginSM: 8,
      margin: 12,
      marginMD: 16,
      marginLG: 20,
      marginXL: 24,
      controlHeight: 28,
      controlHeightLG: 36,
      controlHeightSM: 22,
      fontSizeSM: 12,
    },
    components: {
      Select: {
        activeBorderColor: '#408be9',
        optionSelectedBg: '#1a5bae',
        hoverBorderColor: '#408be9',
        colorBorder: '#3a5e8a',
        hoverBg: 'none',
        activeBg: 'none',
        activeOutlineColor: 'none',
      },
      Input: {
        hoverBg: 'none',
        activeBg: 'none',
        hoverBorderColor: '#408be9',
        colorBorder: '#3a5e8a',
        activeBorderColor: '#408be9',
        activeShadow: 'none',
        paddingBlock: 2,
        paddingInline: 8,
      },
      Dropdown: {
        colorPrimary: '#ffffff',
        controlItemBgActive: '#1a5bae',
        controlItemBgActiveHover: '#1a5bae',
      },
      DatePicker: {
        activeShadow: 'none',
        cellActiveWithRangeBg: '#607a9c'
      },
      Table: {
        headerBorderRadius: 'none',
        headerBg: '#12437e',
        rowSelectedBg: '#1a4477',
        rowHoverBg: '#0f315b',
        rowSelectedHoverBg: '#0f315b',
        headerColor: '#ffffff',
        borderColor: '#374a64',
        rowSelectedText: '#ffffff',
        rowSelectedTextHover: '#ffffff',
        cellPaddingBlock: 8,
        cellPaddingInline: 8,
      },
      Button: {
        primaryShadow: 'none',
        defaultShadow: 'none',
        dangerShadow: 'none',
        paddingInline: 12,
      },
      Alert: {
        colorWarningBg: '#203a65',
        colorWarningBorder: '#4469a5',
      },
      Form: {
        verticalLabelPadding: 2,
      },
      Modal: {
        contentBg: '#19325a',
        contentBgElevated: '#19325a',
        headerBg: '#19325a',
        paddingMD: 16,
      },
      Message: {
        contentBg: '#19325a',
      },
      Radio: {
        buttonColor: '#ffffff',
        buttonCheckedColorDisabled: '#ffffff',
      },
      Collapse: {
        headerBg: '#04274d',
        contentBg: '#000e2f',
        borderlessContentBg: '#000e2f',
      },
      Card: {
        headerBg: '#19325a',
        headerHeight: '42px',
        paddingLG: 16,
      },
      Tooltip: {
        colorBgSpotlight: 'rgba(0,0,0,0.88)',
      },
      Tree: {
        nodeSelectedBg: 'transparent'
      }
    },
    // 自定义主题颜色（用于非 Antd 组件）
    custom: {
      headerBg: 'linear-gradient(to bottom, #164676, #2c73ba)',
      headerBorderBg: 'linear-gradient(to bottom, #0e3f71, #0a3f74,#024378)',
      headerBorderImage: 'linear-gradient(to right, #2c8cbd, #2272a3, #4777a0, #3e5e85, #253b60, #0b1b3c) 1 stretch',
      textColor: '#ffffff',
      layoutBg: '#000e2f',
      noticeBorder: '#fa4546',
      noticeText: '#89cad8',
    },
  },
  // 白色浅色主题
  light: {
    name: 'light',
    cssVar: true,
    token: {
      'borderRadiusLG': 'none',
      'colorBgLayout': '#f0f2f5',
      'colorTextBase': '#333333',
      'colorBgBase': '#ffffff',
      'colorInfoBg': '#e6f7ff',
      'colorPrimary': '#1890ff',
      'colorBorder': '#d9d9d9',
      'colorBgContainer': '#ffffff',
      'colorBgElevated': '#ffffff',
      'borderRadius': 1,
      // 紧凑主题 token
      paddingXXS: 2,
      paddingXS: 4,
      paddingSM: 8,
      padding: 12,
      paddingMD: 16,
      paddingLG: 20,
      paddingXL: 24,
      marginXXS: 2,
      marginXS: 4,
      marginSM: 8,
      margin: 12,
      marginMD: 16,
      marginLG: 20,
      marginXL: 24,
      controlHeight: 28,
      controlHeightLG: 36,
      controlHeightSM: 22,
      fontSizeSM: 12,
    },
    components: {
      Select: {
        activeBorderColor: '#40a9ff',
        optionSelectedBg: '#e6f7ff',
        hoverBorderColor: '#40a9ff',
        colorBorder: '#d9d9d9',
        hoverBg: 'none',
        activeBg: 'none',
        activeOutlineColor: 'none',
      },
      Input: {
        hoverBg: 'none',
        activeBg: 'none',
        hoverBorderColor: '#40a9ff',
        colorBorder: '#d9d9d9',
        activeBorderColor: '#40a9ff',
        activeShadow: 'none',
        paddingBlock: 2,
        paddingInline: 8,
      },
      Dropdown: {
        colorPrimary: '#1890ff',
        controlItemBgActive: '#e6f7ff',
        controlItemBgActiveHover: '#bae7ff',
      },
      DatePicker: {
        activeShadow: 'none',
        cellActiveWithRangeBg: '#e6f7ff'
      },
      Table: {
        headerBorderRadius: 'none',
        headerBg: '#fafafa',
        rowSelectedBg: '#e6f7ff',
        rowHoverBg: '#f5f5f5',
        rowSelectedHoverBg: '#e6f7ff',
        headerColor: '#333333',
        borderColor: '#e8e8e8',
        rowSelectedText: '#333333',
        rowSelectedTextHover: '#333333',
        cellPaddingBlock: 8,
        cellPaddingInline: 8,
      },
      Button: {
        primaryShadow: 'none',
        defaultShadow: 'none',
        dangerShadow: 'none',
        paddingInline: 12,
      },
      Alert: {
        colorWarningBg: '#fffbe6',
        colorWarningBorder: '#ffe58f',
      },
      Form: {
        verticalLabelPadding: 2,
      },
      Modal: {
        contentBg: '#ffffff',
        contentBgElevated: '#ffffff',
        headerBg: '#ffffff',
        paddingMD: 16,
      },
      Message: {
        contentBg: '#ffffff',
      },
      Radio: {
        buttonColor: '#333333',
        buttonCheckedColorDisabled: '#ffffff',
      },
      Collapse: {
        headerBg: '#fafafa',
        contentBg: '#ffffff',
        borderlessContentBg: '#ffffff',
      },
      Card: {
        headerBg: '#fafafa',
        headerHeight: '42px',
        paddingLG: 16,
      },
      Tooltip: {
        colorBgSpotlight: 'rgba(0,0,0,0.75)',
      },
      Tree: {
        nodeSelectedBg: '#e6f7ff'
      }
    },
    // 自定义主题颜色（用于非 Antd 组件）
    custom: {
      headerBg: 'linear-gradient(to bottom, #1890ff, #40a9ff)',
      headerBorderBg: 'linear-gradient(to bottom, #1890ff, #096dd9)',
      headerBorderImage: 'linear-gradient(to right, #1890ff, #40a9ff, #69c0ff, #91d5ff, #bae7ff, #e6f7ff) 1 stretch',
      textColor: '#ffffff',
      layoutBg: '#f0f2f5',
      noticeBorder: '#1890ff',
      noticeText: '#333333',
    },
  },
  // 科技黑主题
  techBlack: {
    name: 'techBlack',
    cssVar: true,
    token: {
      'borderRadiusLG': 'none',
      'colorBgLayout': '#201f2b',
      'colorTextBase': '#89cad8',
      'colorBgBase': '#201f2b',
      'colorInfoBg': '#2a2938',
      'colorPrimary': '#214e85',
      'colorBorder': '#2b4c56',
      'colorBgContainer': '#2a2938',
      'colorBgElevated': '#323141',
      'borderRadius': 1,
      // 紧凑主题 token
      paddingXXS: 2,
      paddingXS: 4,
      paddingSM: 8,
      padding: 12,
      paddingMD: 16,
      paddingLG: 20,
      paddingXL: 24,
      marginXXS: 2,
      marginXS: 4,
      marginSM: 8,
      margin: 12,
      marginMD: 16,
      marginLG: 20,
      marginXL: 24,
      controlHeight: 28,
      controlHeightLG: 36,
      controlHeightSM: 22,
      fontSizeSM: 12,
    },
    components: {
      Select: {
        activeBorderColor: '#3d7ab8',
        optionSelectedBg: '#2d5a8a',
        hoverBorderColor: '#3d7ab8',
        colorBorder: '#2b4c56',
        hoverBg: 'none',
        activeBg: 'none',
        activeOutlineColor: 'none',
      },
      Input: {
        hoverBg: 'none',
        activeBg: 'none',
        hoverBorderColor: '#3d7ab8',
        colorBorder: '#2b4c56',
        activeBorderColor: '#3d7ab8',
        activeShadow: 'none',
        paddingBlock: 2,
        paddingInline: 8,
      },
      Dropdown: {
        colorPrimary: '#89cad8',
        controlItemBgActive: '#2d5a8a',
        controlItemBgActiveHover: '#3d6a9a',
      },
      DatePicker: {
        activeShadow: 'none',
        cellActiveWithRangeBg: '#3d5a7c',
      },
      Table: {
        headerBorderRadius: 'none',
        headerBg: '#2c4452',
        rowSelectedBg: '#2d4560',
        rowHoverBg: '#252d3a',
        rowSelectedHoverBg: '#252d3a',
        headerColor: '#ffffff',
        borderColor: '#2b4c56',
        rowSelectedText: '#89cad8',
        rowSelectedTextHover: '#89cad8',
        cellPaddingBlock: 8,
        cellPaddingInline: 8,
      },
      Button: {
        primaryShadow: 'none',
        defaultShadow: 'none',
        dangerShadow: 'none',
        paddingInline: 12,
      },
      Alert: {
        colorWarningBg: '#2a3848',
        colorWarningBorder: '#2b4c56',
      },
      Form: {
        verticalLabelPadding: 2,
      },
      Modal: {
        contentBg: '#2a2938',
        contentBgElevated: '#2a2938',
        headerBg: '#2a2938',
        paddingMD: 16,
      },
      Message: {
        contentBg: '#2a2938',
      },
      Radio: {
        buttonColor: '#89cad8',
        buttonCheckedColorDisabled: '#89cad8',
      },
      Collapse: {
        headerBg: '#1f1e2a',
        contentBg: '#201f2b',
        borderlessContentBg: '#201f2b',
      },
      Card: {
        headerBg: '#2a2938',
        headerHeight: '42px',
        paddingLG: 16,
      },
      Tooltip: {
        colorBgSpotlight: 'rgba(32, 31, 43, 0.95)',
      },
      Tree: {
        nodeSelectedBg: 'transparent',
      },
    },
    // 自定义主题颜色（用于非 Antd 组件）
    custom: {
      headerBg: 'linear-gradient(to bottom, #1a2a3a, #2c4452)',
      headerBorderBg: 'linear-gradient(to bottom, #1a2d42, #2c4452, #1a3d5a)',
      headerBorderImage: 'linear-gradient(to right, #4a6a8a, #3d5a7a, #2c4452, #1a3d5a, #0f2a3a, #0a1a2a) 1 stretch',
      textColor: '#89cad8',
      layoutBg: '#201f2b',
      noticeBorder: '#4da8d4',
      noticeText: '#89cad8',
    },
  },
};
